# Generated by Django 4.0.5 on 2022-07-05 12:39

import api.v1.products.utils
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(default='-', max_length=250, verbose_name='slug')),
                ('id_1c', models.CharField(blank=True, max_length=200, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='-', max_length=250, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('code_1c', models.CharField(max_length=200, verbose_name='code_1c')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_s', models.ImageField(blank=True, max_length=1200, null=True, upload_to=api.v1.products.utils.l_image_directory_path)),
                ('image_m', models.ImageField(blank=True, max_length=1200, null=True, upload_to=api.v1.products.utils.l_image_directory_path)),
                ('image_l', models.ImageField(blank=True, max_length=1200, null=True, upload_to=api.v1.products.utils.l_image_directory_path)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('type', models.CharField(choices=[('P', 'Products'), ('C', 'Category'), ('B', 'Brands')], default=('P', 'Products'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug')),
                ('sort', models.IntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.color')),
            ],
        ),
        migrations.CreateModel(
            name='Leftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('parent_category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('id_1c', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='-', max_length=250, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(default='-', max_length=250, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('parent_category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size', to='products.category')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.sizetype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('sku', models.CharField(max_length=200, verbose_name='sku')),
                ('slug', models.SlugField(default='-', max_length=250, verbose_name='slug')),
                ('description', models.TextField(default='', max_length=1000)),
                ('collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='collection')),
                ('fashion_collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='fashion_collection')),
                ('price', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('id_1c', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create time ')),
                ('update_by_1c_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('detailed_description', models.TextField(default='', max_length=2000)),
                ('weight', models.CharField(blank=True, max_length=200, null=True, verbose_name='weight')),
                ('width', models.CharField(blank=True, max_length=200, null=True, verbose_name='width')),
                ('height', models.CharField(blank=True, max_length=200, null=True, verbose_name='height')),
                ('volume', models.CharField(blank=True, max_length=200, null=True, verbose_name='volume')),
                ('popularity', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.color')),
                ('image', models.ManyToManyField(blank=True, null=True, related_name='product', to='products.image')),
                ('labels', models.ManyToManyField(blank=True, null=True, to='products.labels')),
                ('leftovers', models.ManyToManyField(blank=True, null=True, related_name='product', to='products.leftover')),
                ('options', models.ManyToManyField(blank=True, null=True, to='products.options')),
                ('related_products', models.ManyToManyField(blank=True, null=True, to='products.product')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.season')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.sex')),
                ('similar_products', models.ManyToManyField(blank=True, null=True, to='products.product')),
                ('tags', models.ManyToManyField(blank=True, to='products.tag')),
                ('variants', models.ManyToManyField(blank=True, null=True, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='leftover',
            name='parent_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.size'),
        ),
        migrations.CreateModel(
            name='Compilations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='subtitle')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('exta_images', models.ManyToManyField(blank=True, null=True, related_name='Compilations', to='products.image')),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='Compilations', to='products.product')),
                ('title_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.image')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.image'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sex', to='products.sex'),
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_icon', to='products.image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_image', to='products.image'),
        ),
    ]
