# Generated by Django 4.0.5 on 2022-07-05 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='subtitle')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug')),
                ('sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sort_id',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sort_id',
            new_name='popularity',
        ),
        migrations.AddField(
            model_name='brand',
            name='id_1c',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='id_1c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sex', to='products.sex'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='-', max_length=250, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_1c',
            field=models.CharField(default='', max_length=200, verbose_name='code_1c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(default='-', max_length=250, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('P', 'Products'), ('C', 'Category'), ('B', 'Brands')], default=('P', 'Products'), max_length=200),
        ),
        migrations.AddField(
            model_name='leftover',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='fashion_collection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='fashion_collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_1c',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=200, verbose_name='sku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', max_length=250, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_by_1c_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='width'),
        ),
        migrations.AddField(
            model_name='season',
            name='id_1c',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(default='-', max_length=250, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='sex',
            name='slug',
            field=models.SlugField(default='-', max_length=250, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='-', max_length=250, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='collection'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='leftovers',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='products.leftover'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.season'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='options',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='products.category'),
        ),
        migrations.AddField(
            model_name='labels',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.color'),
        ),
        migrations.AddField(
            model_name='compilations',
            name='exta_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='Compilations', to='products.image'),
        ),
        migrations.AddField(
            model_name='compilations',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='Compilations', to='products.product'),
        ),
        migrations.AddField(
            model_name='compilations',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='products.labels'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='products.options'),
        ),
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.sizetype'),
        ),
    ]
